global:

  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'trustgraph'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  # The job name is added as a label `job=<job_name>` to any timeseries
  # scraped from this config.

  - job_name: 'trustgraph'

    # Override the global default and scrape targets from this job every
    # 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets:
        - 'pdf-decoder:8000'
        - 'chunker:8000'
        - 'vectorize:8000'
        - 'embeddings:8000'
        - 'kg-extract-definitions:8000'
        - 'kg-extract-relationships:8000'
        - 'store-graph-embeddings:8000'
        - 'store-triples:8000'
        - 'text-completion:8000'
        - 'text-completion-rag:8000'
        - 'graph-rag:8000'
        - 'prompt:8000'
        - 'prompt-rag:8000'
        - 'query-graph-embeddings:8000'
        - 'query-triples:8000'
        - 'pulsar:8080'

